### ISSUE TITLE
URGENT! Node version breaks RC install 3.x

### ISSUE THREAD

**Issue by muhv7** [RocketChat/install.sh#18]
Since RC went with nodejs version 12.x and up the old..old version in ctl will just destroy the whole install. Needs to be updated.

Thank you

**Comment by gabrielsors** [comment]
Same problem here, after "rocketchatctl update" the service is down, in syslog show:

"Meteor requires Node v12.0.0 or later."

After:

```
root@xxxx:~# n latest

  installing : node-v13.9.0
       mkdir : /usr/local/n/versions/node/13.9.0
       fetch : https://nodejs.org/dist/v13.9.0/node-v13.9.0-linux-x64.tar.xz
   installed : v13.9.0 (with npm 6.13.7)

root@sucessocliente:~# node -v
v13.9.0
```

The problem is resolved.
