### ISSUE TITLE
Upgrade option doesn't pull existing version information correctly

### ISSUE THREAD

**Issue by corrigac** [RocketChat/install.sh#28]
sudo rocketchatctl update --version 3.3.0 breaks on a test failure due to incorrect PORT data extraction 

running with -x shows the issue:
+ latest_rocketchat_version=3.3.0commit
+ get_rocketchat_current_version
+ systemctl status rocketchat
++ cat /lib/systemd/system/rocketchat.service
++ grep PORT
++ awk -F= '{print $3}'
+ PORT='mongodb://localhost:27017/rocketchat?replicaSet'
++ curl 'http://localhost:mongodb://localhost:27017/rocketchat?replicaSet/api/info'
++ cut '-d"' -f4
+ current_rocketchat_version=

Line 757 - get_rocketchat_current_version() can mistakenly extract environment settings for Mongodb,  
possible re-write may be:
get_rocketchat_current_version(){

    if PORT=`systemctl status rocketchat | grep Process.Port | awk '{ print $10 }'`; then
        current_rocketchat_version=$(curl http://localhost:$PORT/api/info 2>/dev/null |cut -d\" -f4)
    else
        print_rocketchat_not_running_error_and_exit
    fi
}

**Comment by geekgonecrazy** [comment]
Just out of curiosity did you modify the service file manually?

**Comment by corrigac** [comment]
Yes, as per proposed change

**Comment by geekgonecrazy** [comment]
I mean did you modify it since initial install?  Before the issue.  Or was it untouched since initial install by rocketchatctl.  

Just want to understand if this is an issue that happens with rocketchatctl installer or only if someone modified the file between install and update

**Comment by corrigac** [comment]
Ah, No I'd only touched rocketchatctl after I found that it wasn't working for me.

**Comment by frdmn** [comment]
@corrigac just to rule out a modified systemd unit file... can you copy and paste it here so we can rule out any special characters that might interfer here? What's your exact content of `/lib/systemd/system/rocketchat.service`?

**Comment by corrigac** [comment]
[Unit]

Description=The Rocket.Chat server

After=network.target remote-fs.target nss-lookup.target nginx.target
mongod.target

Wants=network-online.target mongod.target

[Service]

ExecStartPre=/bin/sleep 20

ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js

StandardOutput=syslog

StandardError=syslog

SyslogIdentifier=rocketchat

User=rocketchat

Environment=ROOT_URL=http://rocketchat.############.com/ PORT=3000
MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01
MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01

[Install]

WantedBy=multi-user.target

**Comment by frdmn** [comment]
This is not a default unit file generated by `rocketchatctl` as far as I can tell - which is probably also why the parsing of the specified `PORT` failed previously.

The unit file currently should look like this: https://github.com/RocketChat/install.sh/blob/master/rocketchatctl#L480-L496
