### ISSUE TITLE
404 on installation: bash -c "$(curl https://rocket.chat/install.sh)"

### ISSUE THREAD

**Issue by sjoerdmaessen** [RocketChat/install.sh#30]
The url to the install.sh seems wrong, output when running the command from the repo homepage.

`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                        Dload  Upload   Total   Spent    Left  Speed
100 76433    0 76433    0     0     162k      0 --:--:-- --:--:-- --:--:--  162k
bash: -c: line 0: syntax error near unexpected token `newline'
bash: -c: line 0: `<!doctype html>'`

Visting https://rocket.chat/install.sh manually gives:

404
Houston, we have a problem
The page you are looking for does not exist

**Comment by geekgonecrazy** [comment]
Ouch.. the website was rewrote and seems they didn’t get this file included :(

https://rocketchat.github.io/install.sh can be used temporarily

**Comment by geekgonecrazy** [comment]
Fixed now install.rocket.chat :)
