### ISSUE TITLE
Nginx is in the rocketchat.service

### ISSUE THREAD

**Issue by wreiske** [RocketChat/install.sh#5]
Since this uses traefik or caddy, is nginx needed as a service to wait for?
```
[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.service
```
https://github.com/RocketChat/install.sh/blob/master/rocketchatctl#L401

**Comment by LuluGO** [comment]
thanks! you are right
