### ISSUE TITLE
update wrong check_node_major_version

### ISSUE THREAD

**Issue by xmedeko** [RocketChat/install.sh#61]
`rocketchatctl update` fails with "Error: node version was not updated correctly. Cancelling ..." The reason is wrong `check_node_major_version` function, it has 
```
major_version=${NODE_VERSION:1:2}
```
but should be
```
major_version=${NODE_VERSION:0:2}
```

**Comment by geekgonecrazy** [comment]
Can you propose a PR to fix?

**Comment by xmedeko** [comment]
Yeas, I can to such simple PR, but maybe the content of https://releases.rocket.chat/latest/info has changed - maybe there was something like `"nodeVersion": "v14.18.3"` before? Should be fixed this script or the content of the URL, then?

Also, what about to use more robust
```
major_version=${NODE_VERSION%%.*}
```
